apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app.fullname" . }}-backend
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
    app: {{ include "node-app.fullname" . }}-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.backend }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "node-app.selectorLabels" . | nindent 4 }}
    app: {{ include "node-app.fullname" . }}-backend
