---
replicaCount: 1
image:
  backend:
    repository: danielzerihon/nodejs_backend
    tag: latest  
pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: "nodejs"
service:
  type: ClusterIP
  port:
    backend: 3000
    frontend: 5000
mongodb:
  connectionStringSecret: "mongodb-node-app"
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: nice-assignment.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: nice-assignment-tls
  #    hosts:
  #      - nice-assignment.local